### PR TITLE
Adds CaseType key to v2

### PR DESCRIPTION
**Pull request by riot-act**
**Why?**
TrustEv added a new feature that allows us to differentiate fraud for account creation vs. transaction. See: https://app.trustev.com/Help/Api/POST-api-v2-0-Case

**What?**
Adds the `CaseType` key to create

**Who?**
From your friends at Trunk Club (whom also use TrustEv and are thankful for this gem).

### CODE REVIEW

**Comment by jonahwh** [comment]
Released as [v0.4.0.pre.alpha2](https://github.com/giftcardzen/trustev/tree/v0.4.0.pre.alpha2)

**Comment by riot-act** [comment]
@jonahwh sorry to be a pain but it looks like that tag and gem update doesn't include the commit from this PR. Did I do something incorrectly?

Sorry, took us awhile with our logging to figure out what was going on.

**Comment by jonahwh** [comment]
Sorry about that, I re-released it as `v0.4.0.pre.alpha3`

**Comment by riot-act** [comment]
Awesome. Thank you. Drinks on us if you're ever in Chicago.

**Pull request merged**
